
/**************AUTHENTIFICATION *************/
export const LOGIN = "LOGIN";
export const LOG_OUT = "LOG_OUT";
export const REGISTER = "REGISTER";
export const GET_PROFILE = "GET_PROFILE";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";

export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_REJECTED = "REGISTER_REJECTED";
export const REGISTER_FULFILLED = "REGISTER_FULFILLED";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_PENDING = "FORGOT_PASSWORD_PENDING";
export const FORGOT_PASSWORD_REJECTED = "FORGOT_PASSWORD_REJECTED";
export const FORGOT_PASSWORD_FULFILLED = "FORGOT_PASSWORD_FULFILLED";

export const LOG_OUT_FULLFILED = "LOG_OUT_FULLFILED";
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const GET_PROFILE_REJECTED = "GET_PROFILE_REJECTED";
export const GET_PROFILE_FULFILLED = "GET_PROFILE_FULFILLED";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_PENDING = "UPDATE_PASSWORD_PENDING";
export const UPDATE_PASSWORD_REJECTED = "UPDATE_PASSWORD_REJECTED";
export const UPDATE_PASSWORD_FULFILLED = "UPDATE_PASSWORD_FULFILLED";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_PENDING = "RESET_PASSWORD_PENDING";
export const RESET_PASSWORD_REJECTED = "RESET_PASSWORD_REJECTED";
export const RESET_PASSWORD_FULFILLED = "RESET_PASSWORD_FULFILLED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";
export const UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED";

export const UPDATE_USER_NOTI_TOKEN = "UPDATE_USER_NOTI_TOKEN";
export const UPDATE_USER_NOTI_TOKEN_PENDING = "UPDATE_USER_NOTI_TOKEN_PENDING";
export const UPDATE_USER_NOTI_TOKEN_REJECTED = "UPDATE_USER_NOTI_TOKEN_REJECTED";
export const UPDATE_USER_NOTI_TOKEN_FULFILLED = "UPDATE_USER_NOTI_TOKEN_FULFILLED";
/************************** ORGANISATION **************************/
export const GET_ORGANISATION = 'GET_ORGANISATION';
export const GET_ORGANISATION_PENDING = 'GET_ORGANISATION_PENDING';
export const GET_ORGANISATION_REJECTED = 'GET_ORGANISATION_REJECTED';
export const GET_ORGANISATION_FULFILLED = 'GET_ORGANISATION_FULFILLED';

export const GET_ORGANISATION_BY_USERID = 'GET_ORGANISATION_BY_USERID';
export const GET_ORGANISATION_BY_USERID_PENDING = 'GET_ORGANISATION_BY_USERID_PENDING';
export const GET_ORGANISATION_BY_USERID_REJECTED = 'GET_ORGANISATION_BY_USERID_REJECTED';
export const GET_ORGANISATION_BY_USERID_FULFILLED = 'GET_ORGANISATION_BY_USERID_FULFILLED';

export const GET_ORGANISATION_COUNTRIES = 'GET_ORGANISATION_COUNTRIES';
export const GET_ORGANISATION_COUNTRIES_PENDING = 'GET_ORGANISATION_COUNTRIES_PENDING';
export const GET_ORGANISATION_COUNTRIES_REJECTED = 'GET_ORGANISATION_COUNTRIES_REJECTED';
export const GET_ORGANISATION_COUNTRIES_FULFILLED = 'GET_ORGANISATION_COUNTRIES_FULFILLED';

export const UPDATE_INTERESTS = 'UPDATE_INTERESTS';
export const UPDATE_INTERESTS_PENDING = 'UPDATE_INTERESTS_PENDING';
export const UPDATE_INTERESTS_REJECTED = 'UPDATE_INTERESTS_REJECTED';
export const UPDATE_INTERESTS_FULFILLED = 'UPDATE_INTERESTS_FULFILLED';

export const CHECK_BOURSE = "CHECK_BOURSE";
export const CHECK_CONCOURS = "CHECK_CONCOURS";
export const CHECK_AUTRES = "CHECK_AUTRES";
export const SELECETED_BOURSE = "SELECETED_BOURSE";
export const SELECETED_CONCOURS = "SELECETED_CONCOURS";
export const SELECETED_AUTRES = "SELECETED_AUTRES";

export const SUBMIT_INTERESTS = 'SUBMIT_INTERESTS';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_PENDING = 'GGET_TAGS_PENDING';
export const GGET_TAGS_REJECTED = 'GET_TAGS_REJECTED';
export const GET_TAGS_FULFILLED = 'GET_TAGS_FULFILLED';

/****************************ANNOUNCEMENTS********************/
export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const FIND_FEEDS_BY_TAG_NAME = "FIND_FEEDS_BY_TAG_NAME";
export const GET_ANNOUNCEMENTS_PENDING = 'GET_ANNOUNCEMENTS_PENDING';
export const GET_ANNOUNCEMENTS_REJECTED = 'GET_ANNOUNCEMENTS_REJECTED';
export const GET_ANNOUNCEMENTS_FULFILLED = 'GET_ANNOUNCEMENTS_FULFILLED';
export const GET_SEARCHED_ANNOUNCEMENTS = 'GET_SEARCHED_ANNOUNCEMENTS';
export const GET_SEARCHED_ANNOUNCEMENTS_PENDING = 'GET_SEARCHED_ANNOUNCEMENTS_PENDING';
export const GET_SEARCHED_ANNOUNCEMENTS_REJECTED = 'GET_SEARCHED_ANNOUNCEMENTS_REJECTED';
export const GET_SEARCHED_ANNOUNCEMENTS_FULFILLED = 'GET_SEARCHED_ANNOUNCEMENTS_FULFILLED';

export const SET_ANNOUCEMENT = 'SET_ANNOUCEMENT';
export const SET_ANNOUCEMENT_PENDING = 'SET_ANNOUCEMENT_PENDING';
export const SET_ANNOUCEMENT_REJECTED = 'SET_ANNOUCEMENT_REJECTED';
export const SET_ANNOUCEMENT_FULFILLED = 'SET_ANNOUCEMENT_FULFILLED';

export const GET_ANNOUNCEMENT_BY_ID = 'GET_ANNOUNCEMENT_BY_ID';
export const GET_ANNOUNCEMENT_BY_ID_PENDING = 'GET_ANNOUNCEMENT_BY_ID_PENDING';
export const GET_ANNOUNCEMENT_BY_ID_REJECTED = 'GET_ANNOUNCEMENT_BY_ID_REJECTED';
export const GET_ANNOUNCEMENT_BY_ID_FULFILLED = 'GET_ANNOUNCEMENT_BY_ID_FULFILLED';

export const CKECK_BOOKMARK = 'CKECK_BOOKMARK';
export const SET_SELECTEDITEM = 'SET_SELECTEDITEM';

export const HANDLE_BOOKMARK = 'HANDLE_BOOKMARK';
export const HANDLE_BOOKMARK_PENDING = 'HANDLE_BOOKMARK_PENDING';
export const HANDLE_BOOKMARK_REJECTED = 'HANDLE_BOOKMARK_REJECTED';
export const HANDLE_BOOKMARK_FULFILLED = 'HANDLE_BOOKMARK_FULFILLED';

export const GET_BOOKEMARKED = 'GET_BOOKEMARKED';
export const GET_BOOKEMARKED_PENDING = 'GET_BOOKEMARKED_PENDING';
export const GET_BOOKEMARKED_REJECTED = 'GET_BOOKEMARKED_REJECTED';
export const GET_BOOKEMARKED_FULFILLED = 'GET_BOOKEMARKED_FULFILLED';







/*********************************NOTIFICATIONS ************************************/
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_NOTIFICATION_PENDING = 'SET_NOTIFICATION_PENDING';
export const SET_NOTIFICATION_REJECTED = 'SET_NOTIFICATION_REJECTED';
export const SET_NOTIFICATION_FULFILLED = 'SET_NOTIFICATION_FULFILLED';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_NOTIFICATION_PENDING = 'GET_NOTIFICATION_PENDING';
export const GET_NOTIFICATION_REJECTED = 'GET_NOTIFICATION_REJECTED';
export const GET_NOTIFICATION_FULFILLED = 'GET_NOTIFICATION_FULFILLED';

export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_PENDING = 'UPDATE_NOTIFICATION_PENDING';
export const UPDATE_NOTIFICATION_REJECTED = 'UPDATE_NOTIFICATION_REJECTED';
export const UPDATE_NOTIFICATION_FULFILLED = 'UPDATE_NOTIFICATION_FULFILLED';

/*****************************PERMISSONS *********************************/
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const SET_PERMISSIONS_PENDING = 'SET_PERMISSIONS_PENDING'
export const SET_PERMISSIONS_REJECTED = 'SET_PERMISSIONS_REJECTED'
export const SET_PERMISSIONS_FULFILLED = 'SET_PERMISSIONS_FULFILLED'

export const GET_PERMISSIONS = 'GET_PERMISSIONS'
export const GET_PERMISSIONS_PENDING = 'GET_PERMISSIONS_PENDING'
export const GET_PERMISSIONS_REJECTED = 'GET_PERMISSIONS_REJECTED'
export const GET_PERMISSIONS_FULFILLED = 'GET_PERMISSIONS_FULFILLED'

export const UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS'
export const UPDATE_PERMISSIONS_PENDING = 'UPDATE_PERMISSIONS_PENDING'
export const UPDATE_PERMISSIONS_REJECTED = 'UPDATE_PERMISSIONS_REJECTED'
export const UPDATE_PERMISSIONS_FULFILLED = 'UPDATE_PERMISSIONS_FULFILLED'

export const CHECK_PERMISSION = 'CHECK_PERMISSION'
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE'

